# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - sales-transform-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Path to your Azure Function App project root.
  # This should be the directory containing host.json and your function folders.
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10' # supported: 3.6 to 3.11
  AZURE_WEB_JOBS_STORAGE: ${{ secrets.AZURE_WEB_JOBS_STORAGE }} # This secret should contain your Storage Account connection string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies locally into a .python_packages folder
        run: |
          mkdir -p .python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages
          # Install dependencies into this specific target directory
          pip install --target=".python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages" -r requirements.txt
          # Ensure azure-functions is also there if your code relies on it explicitly being in site-packages
          pip install --target=".python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages" azure-functions

          # --- ADD THIS NEW LINE ---
          echo "Listing contents of .python_packages for verification:"
          ls -R .python_packages
          # ------------------------

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ${{ github.workspace }}

      - name: Unzip artifact
        run: unzip ${{ github.workspace }}/release.zip -d ${{ github.workspace }}/output_package

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E30EA3E8A2FF4903BECAA81CB74C5311 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D117809BE3644E4CA0E4EFF6B39F51B7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8D6A3A189D5845E3B8B0461DED3E37F2 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'sales-transform-func'
          slot-name: 'Production'
          enable-oryx-build: false
          package: ${{ github.workspace }}/output_package
